# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  target 'GitHubUserFetcher' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GItHubUserFetcher

  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'ActionSheetPicker-3.0'

  target 'GitHubUserFetcherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitHubUserFetcherUITests' do
    # Pods for testing
  end

end
